name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  python-package-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
        #"3.10",
        "3.x"] 
    steps:


    - uses: actions/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        submodules: 'true'
    #- name: Set up Python ${{ matrix.python-version }}
    #3  uses: actions/setup-python@v3
    #  with:
    #    architecture: x64
    #    python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install podman-compose
    #- name: Lint with flake8
    #  run: |
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Docker Compose Action build
      #uses: meta-introspector/compose-action@main
      env:
       GITHUB_PAT: ${{ secrets.PAT }}
       GITHUB_REPO: "jmikedupont2/ai-ticket"
      run:         docker-compose build
      

    - name: create openai
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
        GITHUB_REPO: "jmikedupont2/ai-ticket"
      run: |
        GITHUB_PAT=${{ secrets.PAT }} GITHUB_REPO="jmikedupont2/ai-ticket" docker-compose up -d mockopenai
        
    - name: run autogpt
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
        GITHUB_REPO: "jmikedupont2/ai-ticket"
      run: |
        GITHUB_PAT=${{ secrets.PAT }} GITHUB_REPO="jmikedupont2/ai-ticket" docker-compose run autogpt
        
        
